import { buildBudgetEstimatePdf, buildBudgetSheetPdf, buildPdfDocument, clampText, formatCurrency, formatPercent, normalizeDate, safeArray, titleCase } from "../utils.js";
import { generateProposalNarrative, generateReportNarrative } from "./ai.js";

export const generateProposalDocument = async (payload) => {
  const proposalNarrative = await generateProposalNarrative(payload);
  const pdfBuffer = await buildPdfDocument({
    title: "Event Proposal",
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    documentLabel: "Event Proposal",
    date: payload.date || payload.eventDate,
    subject: payload.subject || `Proposal for ${payload.eventTitle || "Event"}`,
    addressedTo: payload.authorityName,
    clubName: payload.clubName,
    bodyParagraphs: proposalNarrative.paragraphs,
    highlights: safeArray(payload.keyPoints),
    footerText: "Generated by DocuPrint Proposal Engine",
    collegeLogo: payload.collegeLogo,
    clubLogo: payload.clubLogo,
    collegeAcronym: payload.collegeAcronym,
    clubAcronym: payload.clubAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    clubBrandColor: payload.clubBrandColor,
    signatories: safeArray(payload.signatories),
  });

  return {
    fileName: `${(payload.eventTitle || "event-proposal").replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      eventTitle: payload.eventTitle,
      clubName: payload.clubName,
      authorityName: payload.authorityName,
      estimatedBudget: payload.budget ? formatCurrency(payload.budget) : null,
      narrativeSource: proposalNarrative.source,
    },
    narrative: proposalNarrative.paragraphs,
    pdfBuffer,
  };
};

export const generateReportDocument = async (payload) => {
  const attendanceRecords = safeArray(payload.attendanceRecords);
  const registeredCount = Number(payload.participantsRegistered || 0) || attendanceRecords.length || 0;
  const appearedCount =
    Number(payload.participantsAppeared || 0) ||
    attendanceRecords.filter((record) => record?.selected !== false).length ||
    attendanceRecords.length ||
    0;
  const namedRecords = attendanceRecords.filter((record) => clampText(record?.name || "", 120));
  const yearCounts = attendanceRecords.reduce((map, record) => {
    const key = clampText(record?.year || "", 20);
    if (key) map.set(key, (map.get(key) || 0) + 1);
    return map;
  }, new Map());
  const branchCounts = attendanceRecords.reduce((map, record) => {
    const key = clampText(record?.branch || "", 40);
    if (key) map.set(key, (map.get(key) || 0) + 1);
    return map;
  }, new Map());
  const divisionCounts = attendanceRecords.reduce((map, record) => {
    const key = clampText(record?.division || "", 20);
    if (key) map.set(key, (map.get(key) || 0) + 1);
    return map;
  }, new Map());

  const mapToBreakdown = (label, entries) =>
    [...entries.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 4)
      .map(([key, value]) => `${label} ${titleCase(key)}: ${value} participants`);

  const attendanceRate = registeredCount > 0 ? appearedCount / registeredCount : 0;
  const completenessRate = attendanceRecords.length > 0 ? namedRecords.length / attendanceRecords.length : 0;

  const analyticsSummary = {
    registeredCount,
    appearedCount,
    rosterCount: attendanceRecords.length,
    attendanceRate,
    attendanceRateFormatted: registeredCount > 0 ? formatPercent(attendanceRate) : "Not available",
    completenessRate,
    completenessFormatted: attendanceRecords.length > 0 ? formatPercent(completenessRate) : "Not available",
    yearCount: yearCounts.size,
    branchCount: branchCounts.size,
    divisionCount: divisionCounts.size,
    attendanceBreakdown: [
      ...(registeredCount > 0 ? [`Registration conversion: ${appearedCount} of ${registeredCount} participants attended`] : []),
      ...(attendanceRecords.length > 0 ? [`Roster records analyzed: ${attendanceRecords.length}`] : []),
      ...mapToBreakdown("Year", yearCounts),
      ...mapToBreakdown("Branch", branchCounts),
      ...mapToBreakdown("Division", divisionCounts),
    ],
  };

  const reportNarrative = await generateReportNarrative({
    ...payload,
    analyticsSummary,
    imageCaptions: safeArray(payload.imageCaptions).length > 0
      ? safeArray(payload.imageCaptions)
      : safeArray(payload.photoDataUrls).map((_value, index) => `Event documentation photograph ${index + 1}`),
  });

  const analytics = [
    registeredCount ? `Registered: ${registeredCount}` : null,
    appearedCount ? `Attended: ${appearedCount}` : null,
    registeredCount > 0 ? `Attendance Rate: ${formatPercent(attendanceRate)}` : null,
    attendanceRecords.length > 0 ? `Roster Records: ${attendanceRecords.length}` : null,
    payload.feedback ? `Feedback: ${payload.feedback}` : null,
    payload.eventFee ? `Event Fee: ${formatCurrency(payload.eventFee)}` : null,
  ].filter(Boolean);

  const pdfBuffer = await buildPdfDocument({
    title: reportNarrative.report?.title || payload.eventName || "Event Report",
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    documentLabel: "Event Report",
    date: payload.date || payload.eventDate,
    subject: payload.subject || payload.eventName || payload.eventTitle || "Event Report",
    addressedTo: payload.eventVenue || payload.authorityName,
    clubName: payload.studentChapterName || payload.clubName,
    bodyParagraphs: [],
    reportSections: reportNarrative.report?.sections || [],
    highlights: safeArray(payload.keyHighlights),
    analytics,
    attendanceInsights: analyticsSummary.attendanceBreakdown,
    footerText: "Generated by DocuPrint Reporting Engine",
    collegeLogo: payload.collegeLogo,
    clubLogo: payload.clubLogo,
    collegeAcronym: payload.collegeAcronym,
    clubAcronym: payload.clubAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    clubBrandColor: payload.clubBrandColor,
    attendanceRecords,
    photoDataUrls: safeArray(payload.photoDataUrls),
    photoCaptions:
      reportNarrative.report?.photoCaptions?.length > 0
        ? reportNarrative.report.photoCaptions
        : safeArray(payload.photoDataUrls).map((_value, index) => `Event documentation photograph ${index + 1}`),
    reportSubtitle: reportNarrative.report?.subtitle || "",
    closingNote: reportNarrative.report?.closingNote || "",
  });

  return {
    fileName: `${(payload.eventName || payload.eventTitle || "event-report").replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      eventTitle: payload.eventName || payload.eventTitle,
      totalAttendees: appearedCount || null,
      attendanceRate: registeredCount > 0 ? formatPercent(attendanceRate) : null,
      narrativeSource: reportNarrative.source,
      keyHighlights: safeArray(payload.keyHighlights),
    },
    pdfBuffer,
  };
};

export const generateBudgetReportDocument = async (payload) => {
  const records = safeArray(payload.records);
  const resolvedTitle =
    payload.title ||
    (records.length === 1 ? `${records[0].title} Budget Report` : "College Budget Expenditure Report");

  const pdfBuffer = await buildBudgetSheetPdf({
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    date: payload.date,
    title: resolvedTitle,
    collegeLogo: payload.collegeLogo,
    collegeAcronym: payload.collegeAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    records,
  });

  return {
    fileName: `${resolvedTitle.replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      title: resolvedTitle,
      records: records.length,
      generatedOn: normalizeDate(payload.date),
    },
    pdfBuffer,
  };
};

export const generateBudgetEstimationDocument = async (payload) => {
  const pdfBuffer = await buildBudgetEstimatePdf({
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    date: payload.date,
    title: payload.title || "Budget Estimation Report",
    collegeLogo: payload.collegeLogo,
    collegeAcronym: payload.collegeAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    eventType: payload.eventType,
    attendees: payload.attendees,
    summary: payload.summary,
    estimatedTotalFormatted: payload.estimatedTotalFormatted,
    breakdown: safeArray(payload.breakdown),
    recommendations: safeArray(payload.recommendations),
  });

  return {
    fileName: `${(payload.title || "budget-estimation-report").replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      title: payload.title || "Budget Estimation Report",
      eventType: payload.eventType || null,
      generatedOn: normalizeDate(payload.date),
    },
    pdfBuffer,
  };
};
